name: automind
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - brian2
  - scikit-learn
  - numba
  - pandas
  - seaborn
  # - pytables
  - h5py  # includes: hdf5
  - pip
  - uv  # fast pip replacement  
  - pip:
      - sbi==0.22.0  # includes: arviz, joblib, matplotlib, numpy, pyknos, pyro-ppl, scipy, torch, tqdm
      - hydra-core
      # - allensdk
      - -e .